In [1]:
# Import the dependencies.
from pathlib import Path
import pandas as pd
import re

# Set the column width. 
pd.options.display.max_colwidth = 100

In [2]:
# Load in the Sherlock Holmes text,

                                text
0  The Adventures of Sherlock Holmes
1              by Arthur Conan Doyle
2                           Contents
3        I.     A Scandal in Bohemia
4       II.    The Red-Headed League

In [3]:
# The \s lets us match any white space and {} lets use match exact ranges or characters.
# Here we find Holmes followed by a space then a 6 letter word then another space.

                                                                         text
214   I rose to go, but Holmes caught me by the wrist and pushed me back into
759   Holmes rushed at the bell-pull, tore back a small sliding shutter, and,
3478   Sherlock Holmes closed his eyes and placed his elbows upon the arms of
3566   Holmes turned over the leaves of the book upon his knee. “Here it is,”
4196      Sherlock Holmes seemed to be embarrassed by the question. “Frankly,
4208    Sherlock Holmes sprang out of his chair as if he had been galvanised.
4934  Holborn. Holmes pushed open the door of the private bar and ordered two
5020      Holmes turned to the page indicated. “Here you are, ‘Mrs. Oakshott,
5027    Sherlock Holmes looked deeply chagrined. He drew a sovereign from his
5080   Sherlock Holmes hailed a four-wheeler which was passing. “In that case
5348            Holmes turned to his desk and, unlocking it, drew out a small
5371           Holmes nodded his head. “The name is familiar to me,” said he.
5579  For answer Holmes pushed back the frill of black lace which fringed the
5585   There was a long silence, during which Holmes leaned his chin upon his
5844    Holmes walked slowly round and examined each and all of them with the
6035    Holmes sprang from the bed, struck a match, and lashed furiously with
6038  But I saw nothing. At the moment when Holmes struck the light I heard a
6733       extraordinary narrative. Then Sherlock Holmes pulled down from the
7296    “And very wet it seems to have made you,” said Holmes laying his hand
7301           Sherlock Holmes leaned back in his chair and laughed heartily.
7366        “Just one hint to you, Lestrade,” drawled Holmes before his rival
7653      to the centre of the room. Sherlock Holmes pushed him down into the
8832   “Let us have everything in its due order.” Holmes thrust his long thin
9224              him, but Sherlock Holmes sprang forward and confronted him.

In [4]:
# Adding a second number to the {} lets us find a range.
# Here it matches all word of length 4 to 6.

                                                                         text
214   I rose to go, but Holmes caught me by the wrist and pushed me back into
327      “Oh, then we have three days yet,” said Holmes with a yawn. “That is
349         Holmes took a note of it. “One other question,” said he. “Was the
650         the voice of Holmes from within assuring them that it was a false
759   Holmes rushed at the bell-pull, tore back a small sliding shutter, and,
819   Bohemia, and how the best plans of Mr. Sherlock Holmes were beaten by a
1250   “Well, Watson,” said Holmes when our visitor had left us, “what do you
1460  injured expression upon his face, while Holmes fell upon his knees upon
1500  which I crouched. Holmes shot the slide across the front of his lantern
2112                                      Holmes with his bright little eyes.
2142     breast, like one who is utterly crushed. Holmes stuck his feet up on
2593   it.” A quick blush passed over her fresh young face as Holmes shot one
2828    Ross, Holmes still carrying with him the stone which he had picked up
2891     Sherlock Holmes took a folded paper from his pocket and flattened it
2979     Holmes rose and sat down at the table with his pen in his hand and a
3071     “God help us!” said Holmes after a long silence. “Why does fate play
3391  Holmes shook his clenched hands in the air. “Incredible imbecility!” he
3397                                           Again Holmes raved in the air.
3416   Holmes moved the lamp, and we both bent over the sheet of paper, which
3478   Sherlock Holmes closed his eyes and placed his elbows upon the arms of
3566   Holmes turned over the leaves of the book upon his knee. “Here it is,”
3645     We sat in silence for some minutes, Holmes more depressed and shaken
3933      of the clouds. Holmes drove in silence, with his head sunk upon his
4196      Sherlock Holmes seemed to be embarrassed by the question. “Frankly,
4208    Sherlock Holmes sprang out of his chair as if he had been galvanised.
4551      I had called upon my friend Sherlock Holmes upon the second morning
4827   When the commissionaire had gone, Holmes took up the stone and held it
4919   “So much for Mr. Henry Baker,” said Holmes when he had closed the door
4934  Holborn. Holmes pushed open the door of the private bar and ordered two
5020      Holmes turned to the page indicated. “Here you are, ‘Mrs. Oakshott,
5027    Sherlock Holmes looked deeply chagrined. He drew a sovereign from his
5080   Sherlock Holmes hailed a four-wheeler which was passing. “In that case
5348            Holmes turned to his desk and, unlocking it, drew out a small
5371           Holmes nodded his head. “The name is familiar to me,” said he.
5554        Holmes shook his head like a man who is far from being satisfied.
5579  For answer Holmes pushed back the frill of black lace which fringed the
5585   There was a long silence, during which Holmes leaned his chin upon his
5802   the house. Holmes drew one of the chairs into a corner and sat silent,
5844    Holmes walked slowly round and examined each and all of them with the
6035    Holmes sprang from the bed, struck a match, and lashed furiously with
6038  But I saw nothing. At the moment when Holmes struck the light I heard a
6733       extraordinary narrative. Then Sherlock Holmes pulled down from the
6999                            “Before the what?” asked Holmes with a start.
7143     Holmes gazed long and earnestly at it. Then he closed the locket and
7289     “What’s up, then?” asked Holmes with a twinkle in his eye. “You look
7296    “And very wet it seems to have made you,” said Holmes laying his hand
7301           Sherlock Holmes leaned back in his chair and laughed heartily.
7366        “Just one hint to you, Lestrade,” drawled Holmes before his rival
7372    He had hardly shut the door behind him when Holmes rose to put on his
7376     It was after five o’clock when Sherlock Holmes left me, but I had no
7552         “The case has been an interesting one,” remarked Holmes when our
7653      to the centre of the room. Sherlock Holmes pushed him down into the
8032    all, being a public, though little used, thoroughfare. Holmes left us
8118     a grey carpet, a large bureau, and a long mirror. Holmes went to the
8125                        Sherlock Holmes took it up and opened the bureau.
8726      Holmes shook his head gravely. “It would cease to be a danger if we
8786                                       But Holmes shook his head gravely.
8832   “Let us have everything in its due order.” Holmes thrust his long thin
9195     “You have done well indeed!” cried Holmes with enthusiasm. “Now lead
9224              him, but Sherlock Holmes sprang forward and confronted him.

In [5]:
# Extract all lines of text containing the word Holmes followed
# by some text of length 6 or greater.

                                                                         text
34        I had seen little of Holmes lately. My marriage had drifted us away
214   I rose to go, but Holmes caught me by the wrist and pushed me back into
260         “Kindly look her up in my index, Doctor,” murmured Holmes without
305           Holmes laughed. “It is quite a pretty little problem,” said he.
345    Holmes scribbled a receipt upon a sheet of his note-book and handed it
...                                                                       ...
8137    “Then I will.” Holmes suddenly bent his strength upon it, but without
8260  With a dazed face the banker made out the required check. Holmes walked
8738  “And she would need to be,” said Holmes gravely. “I am much mistaken if
8832   “Let us have everything in its due order.” Holmes thrust his long thin
9224              him, but Sherlock Holmes sprang forward and confronted him.

[80 rows x 1 columns]

In [6]:
# Create capture groups.


# Extract the groups.

                 0           1
     match
34   0      Holmes      lately
214  0      Holmes      caught
260  0      Holmes     without
305  0      Holmes     laughed
345  0      Holmes   scribbled
...            ...         ...
8137 0      Holmes    suddenly
8260 0      Holmes      walked
8738 0      Holmes     gravely
8832 0      Holmes      thrust
9224 0      Holmes      sprang

[80 rows x 2 columns]

In [7]:
# Grab the value counts for each word in the second capture group.

 quietly         4
 sprang          3
 pushed          3
 answered        3
 blandly         3
 returned        3
 turned          3
 laughed         3
 walked          2
 pulled          2
 chuckled        2
 leaned          2
 clapped         2
 cheerily        2
 suavely         2
 gravely         2
 carelessly      1
 looked          1
 unlocked        1
 hailed          1
 sweetly         1
 glanced         1
 lately          1
 sternly         1
 thoughtfully    1
 nodded          1
 refused         1
 struck          1
 laying          1
 before          1
 stepped         1
 suddenly        1
 standing        1
 interposed      1
 twisted         1
 welcomed        1
 without         1
 scribbled       1
 changed         1
 staggered       1
 rushed          1
 coldly          1
 stopped         1
 remarked        1
 impatient       1
 seemed          1
 continued       1
 demurely        1
 desired         1
 calmly          1
 gently          1
 caught          1
 closed          1
 grinned         1
 thrust          1
Name: 1, dtype: int64

In [8]:
# extract all words that start with 'z' or 'Z'.

                  0
     match
1777 0      Zealand
3500 0         zero
5678 0         zest
8514 0         zero

In [9]:
# Find all the words 6 letters or longer that come after "Holmes" in the text and count their frequency.

 quietly         4
 sprang          3
 pushed          3
 answered        3
 blandly         3
 returned        3
 turned          3
 laughed         3
 walked          2
 pulled          2
 chuckled        2
 leaned          2
 clapped         2
 cheerily        2
 suavely         2
 gravely         2
 carelessly      1
 looked          1
 unlocked        1
 hailed          1
 sweetly         1
 glanced         1
 lately          1
 sternly         1
 thoughtfully    1
 nodded          1
 refused         1
 struck          1
 laying          1
 before          1
 stepped         1
 suddenly        1
 standing        1
 interposed      1
 twisted         1
 welcomed        1
 without         1
 scribbled       1
 changed         1
 staggered       1
 rushed          1
 coldly          1
 stopped         1
 remarked        1
 impatient       1
 seemed          1
 continued       1
 demurely        1
 desired         1
 calmly          1
 gently          1
 caught          1
 closed          1
 grinned         1
 thrust          1
Name: 0, dtype: int64

In [10]:
# Find all the words 6 letters or longer that don't end in "ly" that come after "Holmes"
# in the text and count their frequency.

 answered      3
 returned      3
 pushed        3
 turned        3
 sprang        2
 laughed       2
 pulled        2
 clapped       1
 twisted       1
 hailed        1
 unlocked      1
 caught        1
 nodded        1
 refused       1
 struck        1
 laying        1
 before        1
 walked        1
 leaned        1
 interposed    1
 grinned       1
 closed        1
 without       1
 desired       1
 continued     1
 impatient     1
 welcomed      1
 remarked      1
 stopped       1
 chuckled      1
 rushed        1
 staggered     1
 changed       1
 scribbled     1
 thrust        1
Name: 0, dtype: int64